SELECT
    IMMIGRATION.PORT_CODE as 港コード
    ,PORT_NAME as 港名
    --,KIND_CODE
    --,AMT
    ,sum(CASE WHEN KIND_CODE = '110' THEN AMT ELSE 0 END) as 入国者数
    ,sum(CASE WHEN KIND_CODE = '120' THEN AMT ELSE 0 END) as 出国者数
    ,sum(CASE WHEN KIND_CODE = '110' THEN AMT ELSE 0 END) - sum(CASE WHEN KIND_CODE = '120' THEN AMT ELSE 0 END) as 差分
FROM 
    IMMIGRATION
INNER JOIN PORT ON IMMIGRATION.PORT_CODE = PORT.PORT_CODE
WHERE 
    GROUP_CODE = '120'
GROUP BY
    IMMIGRATION.PORT_CODE
    ,PORT_NAME
HAVING 
    sum(CASE WHEN KIND_CODE = '120' THEN AMT ELSE 0 END) > sum(CASE WHEN KIND_CODE = '120' THEN AMT ELSE 0 END)
ORDER BY 
    差分 desc
    ,IMMIGRATION.PORT_CODE desc 
;
