SELECT
    DISTRICT_CODE as CODE
    ,DISTRICT_NAME as 'NAME'
    ,TOTAL_AMT as TOTAL
FROM
    POPULATION
WHERE
    TOTAL_AMT >= 100000 and
    DISTRICT_NAME like '%東%'
ORDER BY
    TOTAL DESC,CODE ASC
;
